POKEMON_ES_TO_TCG = {
    # GENERACIÓN I
    "bisasam": "Bulbasaur",
    "bisaknosp": "Ivysaur",
    "bisaknostra": "Venusaur",
    "charmander": "Charmander",
    "charmeleon": "Charmeleon",
    "charizard": "Charizard",
    "esquirtle": "Squirtle",
    "wartortle": "Wartortle",
    "blastoise": "Blastoise",
    "caterpie": "Caterpie",
    "metapod": "Metapod",
    "beedrill": "Beedrill",
    "pidgeot": "Pidgeot",
    "pidgeotto": "Pidgeotto",
    "pidgeot": "Pidgeot",
    "rattata": "Rattata",
    "raticate": "Raticate",
    "spearow": "Spearow",
    "fearow": "Fearow",
    "ekans": "Ekans",
    "arbok": "Arbok",
    "pikachu": "Pikachu",
    "raichu": "Raichu",
    "alola raichu": "Alolan Raichu",
    "meowth": "Meowth",
    "alola meowth": "Alolan Meowth",
    "persian": "Persian",
    "psyduck": "Psyduck",
    "golduck": "Golduck",
    "mankey": "Mankey",
    "primeape": "Primeape",
    "annihilape": "Annihilape",
    "growlithe": "Growlithe",
    "arcanine": "Arcanine",
    "poliwag": "Poliwag",
    "poliwhirl": "Poliwhirl",
    "poliwrath": "Poliwrath",
    "abra": "Abra",
    "kadabra": "Kadabra",
    "alakazam": "Alakazam",
    "machop": "Machop",
    "machoke": "Machoke",
    "machamp": "Machamp",
    "bellsprout": "Bellsprout",
    "weepinbell": "Weepinbell",
    "victreebel": "Victreebel",
    "tentacool": "Tentacool",
    "tentacruel": "Tentacruel",
    "slowpoke": "Slowpoke",
    "slowbro": "Slowbro",
    "slowking": "Slowking",
    "seel": "Seel",
    "dewgong": "Dewgong",
    "shellder": "Shellder",
    "cloyster": "Cloyster",
    "gastly": "Gastly",
    "haunter": "Haunter",
    "gengar": "Gengar",
    "onix": "Onix",
    "steelix": "Steelix",
    "drowzee": "Drowzee",
    "hypno": "Hypno",
    "krabby": "Krabby",
    "kingler": "Kingler",
    "voltorb": "Voltorb",
    "electrode": "Electrode",
    "exeggcute": "Exeggcute",
    "exeggutor": "Exeggutor",
    "alola exeggutor": "Alolan Exeggutor",
    "cubone": "Cubone",
    "marowak": "Marowak",
    "alola marowak": "Alolan Marowak",
    "hitmonlee": "Hitmonlee",
    "hitmonchan": "Hitmonchan",
    "hitmonlee": "Hitmonlee",
    "lickitung": "Lickitung",
    "lickilicky": "Lickilicky",
    "rhyhorn": "Rhyhorn",
    "rhydon": "Rhydon",
    "rhyperior": "Rhyperior",
    "chansey": "Chansey",
    "blissey": "Blissey",
    "kangaskhan": "Kangaskhan",
    "horsea": "Horsea",
    "seadragon": "Seadra",
    "kingdra": "Kingdra",
    "goldeen": "Goldeen",
    "seaking": "Seaking",
    "staryu": "Staryu",
    "starmie": "Starmie",
    "señor mime": "Mr. Mime",
    "mr. mime": "Mr. Mime",
    "scyther": "Scyther",
    "scizor": "Scizor",
    "jynx": "Jynx",
    "electabuzz": "Electabuzz",
    "electivire": "Electivire",
    "magby": "Magby",
    "magnemite": "Magnemite",
    "magneton": "Magneton",
    "magnezone": "Magnezone",
    "farfetchd": "Farfetch'd",
    "doduo": "Doduo",
    "dodrio": "Dodrio",
    "lickitung": "Lickitung",
    "weedle": "Weedle",
    "kakuna": "Kakuna",
    "beedrill": "Beedrill",
    "venonat": "Venonat",
    "venomoth": "Venomoth",
    "diglett": "Diglett",
    "alola diglett": "Alolan Diglett",
    "dugtrio": "Dugtrio",
    "alola dugtrio": "Alolan Dugtrio",
    "grimer": "Grimer",
    "muk": "Muk",
    "alola muk": "Alolan Muk",
    "paras": "Paras",
    "parasect": "Parasect",
    "venonat": "Venonat",
    "venomoth": "Venomoth",
    "oddish": "Oddish",
    "gloom": "Gloom",
    "vileplume": "Vileplume",
    "bellossom": "Bellossom",
    "lapras": "Lapras",
    "ditto": "Ditto",
    "eevee": "Eevee",
    "vaporeon": "Vaporeon",
    "jolteon": "Jolteon",
    "flareon": "Flareon",
    "espeon": "Espeon",
    "umbreon": "Umbreon",
    "leafeon": "Leafeon",
    "glaceon": "Glaceon",
    "sylveon": "Sylveon",
    "porygon": "Porygon",
    "porygon2": "Porygon2",
    "porygon-z": "Porygon-Z",
    "omanyte": "Omanyte",
    "omastar": "Omastar",
    "kabuto": "Kabuto",
    "kabutops": "Kabutops",
    "aerodactyl": "Aerodactyl",
    "snorlax": "Snorlax",
    "articuno": "Articuno",
    "zapdos": "Zapdos",
    "moltres": "Moltres",
    "dratini": "Dratini",
    "dragonair": "Dragonair",
    "dragonite": "Dragonite",
    "mewtwo": "Mewtwo",
    "mew": "Mew",
    
    # GENERACIÓN II
    "chikorita": "Chikorita",
    "bayleef": "Bayleef",
    "meganium": "Meganium",
    "cyndaquil": "Cyndaquil",
    "quilava": "Quilava",
    "typhlosion": "Typhlosion",
    "totodile": "Totodile",
    "croconaw": "Croconaw",
    "feraligatr": "Feraligatr",
    "sentret": "Sentret",
    "furret": "Furret",
    "hoothoot": "Hoothoot",
    "noctowl": "Noctowl",
    "ledyba": "Ledyba",
    "ledian": "Ledian",
    "spinarak": "Spinarak",
    "girafarig": "Girafarig",
    "mareep": "Mareep",
    "flaaffy": "Flaaffy",
    "ampharos": "Ampharos",
    "marill": "Marill",
    "azumarill": "Azumarill",
    "azurmarui": "Azumarill",
    "sudowoodo": "Sudowoodo",
    "politoed": "Politoed",
    "hoppip": "Hoppip",
    "skiploom": "Skiploom",
    "jumpluff": "Jumpluff",
    "aipom": "Aipom",
    "ambipom": "Ambipom",
    "sunkern": "Sunkern",
    "sunflora": "Sunflora",
    "yanma": "Yanma",
    "yanmega": "Yanmega",
    "wooper": "Wooper",
    "clodsire": "Clodsire",
    "quagsire": "Quagsire",
    "espeon": "Espeon",
    "umbreon": "Umbreon",
    "murkrow": "Murkrow",
    "honchkrow": "Honchkrow",
    "misdreavus": "Misdreavus",
    "mismagius": "Mismagius",
    "unown": "Unown",
    "wobbuffet": "Wobbuffet",
    "wynaut": "Wynaut",
    "pineco": "Pineco",
    "forretress": "Forretress",
    "dunsparce": "Dunsparce",
    "corsola": "Corsola",
    "remoraid": "Remoraid",
    "octillery": "Octillery",
    "mantine": "Mantine",
    "mantyke": "Mantyke",
    "skarmory": "Skarmory",
    "houndour": "Houndour",
    "houndoom": "Houndoom",
    "kingdra": "Kingdra",
    "phanpy": "Phanpy",
    "donphan": "Donphan",
    "porygon2": "Porygon2",
    "steelix": "Steelix",
    "scizor": "Scizor",
    "shiny": "Shiny",
    "celebi": "Celebi",
    
    # GENERACIÓN III
    "treecko": "Treecko",
    "grovyle": "Grovyle",
    "sceptile": "Sceptile",
    "torchic": "Torchic",
    "combusken": "Combusken",
    "blaziken": "Blaziken",
    "mudkip": "Mudkip",
    "marshtomp": "Marshtomp",
    "swampert": "Swampert",
    "poochyena": "Poochyena",
    "mightyena": "Mightyena",
    "zigzagoon": "Zigzagoon",
    "linoone": "Linoone",
    "wurmple": "Wurmple",
    "silcoon": "Silcoon",
    "beautifly": "Beautifly",
    "cascoon": "Cascoon",
    "dustox": "Dustox",
    "lotad": "Lotad",
    "lombre": "Lombre",
    "ludicolo": "Ludicolo",
    "seedot": "Seedot",
    "nuzleaf": "Nuzleaf",
    "shiftry": "Shiftry",
    "taillow": "Taillow",
    "swellow": "Swellow",
    "wingull": "Wingull",
    "pelipper": "Pelipper",
    "ralts": "Ralts",
    "kirlia": "Kirlia",
    "gardevoir": "Gardevoir",
    "gallade": "Gallade",
    "surskit": "Surskit",
    "masquerain": "Masquerain",
    "shroomish": "Shroomish",
    "breloom": "Breloom",
    "slakoth": "Slakoth",
    "vigoroth": "Vigoroth",
    "slaking": "Slaking",
    "nincada": "Nincada",
    "ninjask": "Ninjask",
    "shedinja": "Shedinja",
    "whismur": "Whismur",
    "loudred": "Loudred",
    "exploud": "Exploud",
    "skitty": "Skitty",
    "delcatty": "Delcatty",
    "spinda": "Spinda",
    "zangoose": "Zangoose",
    "castform": "Castform",
    "kecleon": "Kecleon",
    "shuppet": "Shuppet",
    "banette": "Banette",
    "duskull": "Duskull",
    "dusclops": "Dusclops",
    "dusknoir": "Dusknoir",
    "tropius": "Tropius",
    "chimecho": "Chimecho",
    "chingling": "Chingling",
    "absol": "Absol",
    "snorunt": "Snorunt",
    "glalie": "Glalie",
    "froslass": "Froslass",
    "spheal": "Spheal",
    "sealeo": "Sealeo",
    "walrein": "Walrein",
    "clamperl": "Clamperl",
    "huntail": "Huntail",
    "gorebyss": "Gorebyss",
    "relicanth": "Relicanth",
    "luvdisc": "Luvdisc",
    "bagon": "Bagon",
    "shelgon": "Shelgon",
    "salamence": "Salamence",
    "beldum": "Beldum",
    "metang": "Metang",
    "metagross": "Metagross",
    "regirock": "Regirock",
    "regice": "Regice",
    "registeel": "Registeel",
    "latias": "Latias",
    "latios": "Latios",
    "kyogre": "Kyogre",
    "groudon": "Groudon",
    "rayquaza": "Rayquaza",
    "jirachi": "Jirachi",
    "deoxys": "Deoxys",
    
    # GENERACIÓN IV
    "turtwig": "Turtwig",
    "grotle": "Grotle",
    "torterra": "Torterra",
    "chimchar": "Chimchar",
    "monferno": "Monferno",
    "infernape": "Infernape",
    "piplup": "Piplup",
    "prinplup": "Prinplup",
    "empoleon": "Empoleon",
    "starly": "Starly",
    "staravia": "Staravia",
    "staraptor": "Staraptor",
    "bidoof": "Bidoof",
    "bibarel": "Bibarel",
    "buizel": "Buizel",
    "floatzel": "Floatzel",
    "cherubi": "Cherubi",
    "cherrim": "Cherrim",
    "shellos": "Shellos",
    "gastrodon": "Gastrodon",
    "drifloon": "Drifloon",
    "drifblim": "Drifblim",
    "buneary": "Buneary",
    "lopunny": "Lopunny",
    "glameow": "Glameow",
    "purugly": "Purugly",
    "chatot": "Chatot",
    "spiritomb": "Spiritomb",
    "gible": "Gible",
    "gabite": "Gabite",
    "garchomp": "Garchomp",
    "munchlax": "Munchlax",
    "riolu": "Riolu",
    "lucario": "Lucario",
    "hippopotas": "Hippopotas",
    "hippowdon": "Hippowdon",
    "skorupi": "Skorupi",
    "drapion": "Drapion",
    "croagunk": "Croagunk",
    "toxicroak": "Toxicroak",
    "carnivine": "Carnivine",
    "mamoswine": "Mamoswine",
    "leafeon": "Leafeon",
    "glaceon": "Glaceon",
    "rhyperior": "Rhyperior",
    "tangrowth": "Tangrowth",
    "electivire": "Electivire",
    "magmortar": "Magmortar",
    "togekiss": "Togekiss",
    "yanmega": "Yanmega",
    "gliscor": "Gliscor",
    "mamoswine": "Mamoswine",
    "porygon-z": "Porygon-Z",
    "gallade": "Gallade",
    "probopass": "Probopass",
    "dusknoir": "Dusknoir",
    "froslass": "Froslass",
    "rotom": "Rotom",
    "uxie": "Uxie",
    "mesprit": "Mesprit",
    "azelf": "Azelf",
    "dialga": "Dialga",
    "palkia": "Palkia",
    "heatran": "Heatran",
    "regigigas": "Regigigas",
    "giratina": "Giratina",
    "cresselia": "Cresselia",
    "phione": "Phione",
    "manaphy": "Manaphy",
    "darkrai": "Darkrai",
    "shaymin": "Shaymin",
    "arceus": "Arceus",
    
    # GENERACIÓN V
    "snivy": "Snivy",
    "servine": "Servine",
    "serperior": "Serperior",
    "tepig": "Tepig",
    "pignite": "Pignite",
    "emboar": "Emboar",
    "oshawott": "Oshawott",
    "dewott": "Dewott",
    "samurott": "Samurott",
    "patrat": "Patrat",
    "watchog": "Watchog",
    "lillipup": "Lillipup",
    "herdier": "Herdier",
    "stoutland": "Stoutland",
    "pidove": "Pidove",
    "tranquill": "Tranquill",
    "unfezant": "Unfezant",
    "blitzle": "Blitzle",
    "zebstrika": "Zebstrika",
    "roggenrola": "Roggenrola",
    "boldore": "Boldore",
    "gigalith": "Gigalith",
    "woobat": "Woobat",
    "swoobat": "Swoobat",
    "drilbur": "Drilbur",
    "excadrill": "Excadrill",
    "audino": "Audino",
    "timburr": "Timburr",
    "gurdurr": "Gurdurr",
    "conkeldurr": "Conkeldurr",
    "tympole": "Tympole",
    "palpitoad": "Palpitoad",
    "seismitoad": "Seismitoad",
    "throh": "Throh",
    "sawk": "Sawk",
    "sewaddle": "Sewaddle",
    "swadloon": "Swadloon",
    "leavanny": "Leavanny",
    "venipede": "Venipede",
    "whirlipede": "Whirlipede",
    "scolipede": "Scolipede",
    "cottonee": "Cottonee",
    "whimsicott": "Whimsicott",
    "petilil": "Petilil",
    "lilligant": "Lilligant",
    "basculin": "Basculin",
    "sandile": "Sandile",
    "krokonaw": "Krookodile",
    "krookodile": "Krookodile",
    "maractus": "Maractus",
    "dwebble": "Dwebble",
    "crustle": "Crustle",
    "scraggy": "Scraggy",
    "scrafty": "Scrafty",
    "sigilyph": "Sigilyph",
    "yamask": "Yamask",
    "cofagrigus": "Cofagrigus",
    "tirtouga": "Tirtouga",
    "carracosta": "Carracosta",
    "archen": "Archen",
    "archeops": "Archeops",
    "trubbish": "Trubbish",
    "garbodor": "Garbodor",
    "zorua": "Zorua",
    "zoroark": "Zoroark",
    "minccino": "Minccino",
    "cinccino": "Cinccino",
    "ducklett": "Ducklett",
    "swanna": "Swanna",
    "vanillite": "Vanillite",
    "vanillish": "Vanillish",
    "vanilluxe": "Vanilluxe",
    "deerling": "Deerling",
    "sawsbuck": "Sawsbuck",
    "emolga": "Emolga",
    "joltik": "Joltik",
    "galvantula": "Galvantula",
    "ferroseed": "Ferroseed",
    "ferrothorn": "Ferrothorn",
    "klink": "Klink",
    "klang": "Klang",
    "klinklang": "Klinklang",
    "tynamo": "Tynamo",
    "eelektrik": "Eelektrik",
    "eelektross": "Eelektross",
    "elgyem": "Elgyem",
    "beheeyem": "Beheeyem",
    "litwick": "Litwick",
    "lampent": "Lampent",
    "chandelure": "Chandelure",
    "axew": "Axew",
    "fraxure": "Fraxure",
    "haxorus": "Haxorus",
    "cubchoo": "Cubchoo",
    "beartic": "Beartic",
    "cryogonal": "Cryogonal",
    "shelmet": "Shelmet",
    "accelgor": "Accelgor",
    "stunfisk": "Stunfisk",
    "mienfoo": "Mienfoo",
    "mienshao": "Mienshao",
    "druddigon": "Druddigon",
    "golett": "Golett",
    "golurk": "Golurk",
    "pawniard": "Pawniard",
    "bisharp": "Bisharp",
    "bouffalant": "Bouffalant",
    "rufflet": "Rufflet",
    "braviary": "Braviary",
    "vullaby": "Vullaby",
    "mandibuzz": "Mandibuzz",
    "heatmor": "Heatmor",
    "durant": "Durant",
    "deino": "Deino",
    "zweilous": "Zweilous",
    "hydreigon": "Hydreigon",
    "larvesta": "Larvesta",
    "volcarona": "Volcarona",
    "cobalion": "Cobalion",
    "terrakion": "Terrakion",
    "virizion": "Virizion",
    "tornadus": "Tornadus",
    "thundurus": "Thundurus",
    "reshiram": "Reshiram",
    "zekrom": "Zekrom",
    "landorus": "Landorus",
    "kyurem": "Kyurem",
    "keldeo": "Keldeo",
    "meloetta": "Meloetta",
    "genesect": "Genesect",
    
    # GENERACIÓN VI - VII - VIII - IX
    "greninja": "Greninja",
    "talonflame": "Talonflame",
    "vivillon": "Vivillon",
    "pyroar": "Pyroar",
    "furfrou": "Furfrou",
    "floette": "Floette",
    "florges": "Florges",
    "gogoat": "Gogoat",
    "pangoro": "Pangoro",
    "pancham": "Pancham",
    "clawitzer": "Clawitzer",
    "clauncher": "Clauncher",
    "aegislash": "Aegislash",
    "aromatisse": "Aromatisse",
    "spritzee": "Spritzee",
    "slurpuff": "Slurpuff",
    "swirlix": "Swirlix",
    "barbaracle": "Barbaracle",
    "binacle": "Binacle",
    "helioptile": "Helioptile",
    "heliolisk": "Heliolisk",
    "tyrantrum": "Tyrantrum",
    "tyrunt": "Tyrunt",
    "aurorus": "Aurorus",
    "amaura": "Amaura",
    "sylveon": "Sylveon",
    "hawlucha": "Hawlucha",
    "goodra": "Goodra",
    "sliggoo": "Sliggoo",
    "goomy": "Goomy",
    "kommo-o": "Kommo-o",
    "hakamo-o": "Hakamo-o",
    "jangmo-o": "Jangmo-o",
    "klefki": "Klefki",
    "trevenant": "Trevenant",
    "phantump": "Phantump",
    "gourgeist": "Gourgeist",
    "pumpkaboo": "Pumpkaboo",
    "avalugg": "Avalugg",
    "bergmite": "Bergmite",
    "noivern": "Noivern",
    "noibat": "Noibat",
    "xerneas": "Xerneas",
    "yveltal": "Yveltal",
    "zygarde": "Zygarde",
    "diancie": "Diancie",
    "hoopa": "Hoopa",
    "volcanion": "Volcanion",
    "primarina": "Primarina",
    "brionne": "Brionne",
    "popplio": "Popplio",
    "decidueye": "Decidueye",
    "dartrix": "Dartrix",
    "rowlet": "Rowlet",
    "incineroar": "Incineroar",
    "torracat": "Torracat",
    "litten": "Litten",
    "mimikyu": "Mimikyu",
    "mimikyu": "Mimikyu",
    "dragapult": "Dragapult",
    "drakloak": "Drakloak",
    "dreepy": "Dreepy",
    "duraludon": "Duraludon",
    "corviknight": "Corviknight",
    "corvisquire": "Corvisquire",
    "rookidee": "Rookidee",
    "cinderace": "Cinderace",
    "raboot": "Raboot",
    "scorbunny": "Scorbunny",
    "rillaboom": "Rillaboom",
    "thwackey": "Thwackey",
    "grookey": "Grookey",
    "inteleon": "Inteleon",
    "drizzile": "Drizzile",
    "sobble": "Sobble",
    "arboliva": "Arboliva",
    "dolliv": "Dolliv",
    "smoliv": "Smoliv",
    "ceruledge": "Ceruledge",
    "armarouge": "Armarouge",
    "charcadet": "Charcadet",
    "greatusk": "Great Tusk",
    "screamtail": "Scream Tail",
    "brutebonnet": "Brute Bonnet",
    "fluttermane": "Flutter Mane",
    "slitherwing": "Slither Wing",
    "sandyshocks": "Sandy Shocks",
    "roaringmoon": "Roaring Moon",
    "walkingwake": "Walking Wake",
    "colmilargo": "Great Tusk",
    "colagrito": "Scream Tail",
    "furioseta": "Brute Bonnet",
    "melenaleteo": "Flutter Mane",
    "reptalada": "Slither Wing",
    "pelarena": "Sandy Shocks",
    "bramaluna": "Roaring Moon",
    "ondulagua": "Walking Wake",
    "iron treads": "Iron Treads",
    "iron bundle": "Iron Bundle",
    "iron hands": "Iron Hands",
    "iron jugulis": "Iron Jugulis",
    "iron moth": "Iron Moth",
    "iron thorns": "Iron Thorns",
    "iron valiant": "Iron Valiant",
    "iron leaves": "Iron Leaves",
    "iron boulder": "Iron Boulder",
    "iron crown": "Iron Crown",
    "ferrodada": "Iron Treads",
    "ferrosaco": "Iron Bundle",
    "ferropalmas": "Iron Hands",
    "ferrocuello": "Iron Jugulis",
    "ferropolilla": "Iron Moth",
    "ferropúas": "Iron Thorns",
    "ferropaladín": "Iron Valiant",
    "ferroverdor": "Iron Leaves",
    "ferromole": "Iron Boulder",
    "ferrotesta": "Iron Crown",
    
    # ENTRENADORES / TRAINERS EN ESPAÑOL
    "ornitologo": "Bird Keeper",
    "ornitologa": "Bird Keeper",
    "profesor": "Professor",
    "enfermera joy": "Nurse Joy",
    "oficial jenny": "Officer Jenny",
    "entrenador": "Trainer",
    "as": "Ace Trainer",
    "joven": "Lass",
    "chaval": "Youngster",
    "belleza": "Beauty",
    "marinero": "Sailor",
    "montañero": "Hiker",
    "psiquico": "Psychic",
    "jugador": "Gambler",
    "cientifico": "Scientist",
    "enfermera": "Nurse",
    "medico": "Doctor",
    "centro pokémon": "Pokémon Center",
    "pocion": "Potion",
    "antídoto": "Antidote",
    "revivir": "Revive",
    "pokéball": "Poké Ball",
    "superball": "Great Ball",
    "ultrabola": "Ultra Ball",
    "luz ultravioleta": "UV Light",
    "pokebola": "Poké Ball",
    "super pocion": "Super Potion",
    "hiperpocion": "Hyper Potion",
    "pocion completa": "Full Restore",
    "revivir": "Revive",
    "revival completo": "Full Revive",
    "repelente": "Repel",
    "superrepelente": "Super Repel",
    "maxirepelente": "Max Repel",
    "centro pokemon": "Pokémon Center",
    "ventanilla venta": "Poké Mart",
    "entrenador ace": "Ace Trainer",
    "campeón": "Champion",
    "lider gimnasio": "Gym Leader",
    "elite four": "Elite Four",
}

TCG_TERMS = {
        # Tipos de carta
        "energia": "energy", "energía": "energy",
        "entrenador": "trainer", "objeto": "item",
        "partidario": "supporter", "estadio": "stadium",
        "herramienta": "tool", "pocion": "potion", "poción": "potion",
        "pokeball": "poke ball", "pokéball": "poke ball",
        
        # Mecánicas y rarezas (¡Crucial para el orden!)
        "radiante": "radiant",
        "brillante": "shining",
        "dorada": "gold",
        "dorado": "gold",
        "arcoiris": "rainbow",
        "arco iris": "rainbow",
    }


import requests
from django.core.cache import cache

# En tu archivo cards/utils.py

def get_filter_options(filter_type): # <--- Asegúrate de que tenga (endpoint) aquí
    """Obtiene datos de la API y los guarda en caché durante 24 horas."""
    cache_key = f"api_options_{filter_type}"
    options = cache.get(cache_key)
    
    if not options:
        try:
            url = f"https://api.pokemontcg.io/v2/{filter_type}"
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                data = response.json().get('data', [])
                # Si es una lista de strings simple, sorted(data) está bien.
                # Si son objetos, necesitarás sorted(data, key=lambda x: x)
                options = sorted(data)
                cache.set(cache_key, options, 86400)
        except Exception:
            options = [] 
    return options