# Generated by Django 6.0.6 on 2026-07-14 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_remove_pricehistory_source_pricehistory_marketplace_and_more"),
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pricehistory",
            name="alerts_pric_card_id_aea805_idx",
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="date",
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 7, 14)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="pricehistory",
            unique_together={("card", "date")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(fields=["card", "date"], name="alerts_pric_card_id_739719_idx"),
        ),
    ]
