# Generated by Django 6.0.6 on 2026-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemontcg_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('uncommon', 'Infrecuente'), ('rare', 'Rara'), ('holorare', 'Holo Rara')], default='common', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
