# Generated by Django 6.0.6 on 2026-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pokedex', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.URLField()),
            ],
            options={
                'verbose_name': 'Especie Pokémon',
                'verbose_name_plural': 'Especies Pokémon',
                'ordering': ['numero_pokedex'],
            },
        ),
    ]
